name: Rubocop

on:
  pull_request:
  push:
    branches:
    - main
    - release**

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
      - run: bundle install
      - name: Rubocop
        run: rubocop
